# Generated by Django 6.0.7 on 2026-07-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('listing1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_listing1', to='listings.listing')),
                ('listing2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_listing2', to='listings.listing')),
            ],
        ),
    ]
