# Generated by Django 6.0.7 on 2026-07-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offer', 'Offer'), ('request', 'Request')], max_length=10)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('language', 'Language'), ('music', 'Music'), ('cooking', 'Cooking'), ('sports', 'Sports'), ('art', 'Art'), ('academic', 'Academic'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('radius_km', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('active', 'Active')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
