# Generated by Django 6.0.7 on 2026-07-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_photo_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='latitue',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='photo',
        ),
    ]
